@host=http://127.0.0.1:5000

#### T R A N S A C T I O N S
### Create an item
POST {{host}}/transactions
Content-Type: application/json

{
    "budget_id": 3,
    "amount": 100.00,
    "description": "Grocery shopping",
    "trans_date": "2023-12-10",
    "user_id": 5
}

### Read all items
GET {{host}}/transactions
Content-Type: application/json

### Read single item by id
GET {{host}}/transactions/5
Content-Type: application/json

### Update an item
PUT {{host}}/transactions/5
Content-Type: application/json 
 
{
    "budget_id": 2,
    "amount": 1000.00,
    "description": "Shopping",
    "trans_date": "2023-12-10",
    "user_id": 5
}

### Delete an item
DELETE {{host}}/transactions/5
Content-Type: application/json


#### B U D G E T S
### Create an item
POST {{host}}/budgets
Content-Type: application/json

{
    "category": "TESTING",
    "amount": "10000.00",
    "user_id": 3
} 

### Read all items
GET {{host}}/budgets
Content-Type: application/json

### Read single item by id
GET {{host}}/budgets/2
Content-Type: application/json

### Update an item
PUT {{host}}/budgets/2
Content-Type: application/json 
 
{
    "category": "TEST",
    "amount": "1000.00",
    "user_id": 3
}

### Delete an item
DELETE {{host}}/budgets/12
Content-Type: application/json

#### U S E R S

### Create an item
POST {{host}}/users
Content-Type: application/json

{
  "username": "john_doe1",
  "password": "secure_password1",
  "email": "john.doe@example.com1"
}

### Read all items
GET {{host}}/users
Content-Type: application/json

### Read single item by id
GET {{host}}/users/1
Content-Type: application/json

### Update an item
PUT {{host}}/users/1
Content-Type: application/json

{
  "new_username": "updated_john_doe",
  "new_password": "updated_secure_password",
  "new_email": "updated_john.doe@example.com"
}

### Delete an item
DELETE {{host}}/users/1
Content-Type: application/json


